### ISSUE TITLE
Fail to locate the anchor when id is not a valid css selector

### ISSUE THREAD

**Issue by gyhyfj** [vuejs/vitepress#1039]
### Describe the bug

If the md file’s h2 title start with special character,
page can't scroll to the right place as usual when I click toc in `.VPDocAsideOutline` ,   on the right side of the web,

### Reproduction

For example:
The md file is like this:
```md
# Reading
...
... 
## `- + * /`
...
...
```

If I click toc in `.VPDocAsideOutline` , on the right side of the web,
the page can't scroll to the right place as usual.
Chrome terminal report :
```js
DOMException: Failed to execute 'querySelector' on 'Document': '#-5' is not a valid selector.
    at c (https://www.gyhyfj.com/assets/app.4bd937d4.js:1:124560)
    at $t (https://www.gyhyfj.com/assets/app.4bd937d4.js:1:12734)
    at qe (https://www.gyhyfj.com/assets/app.4bd937d4.js:1:12813)
    at HTMLAnchorElement.n (https://www.gyhyfj.com/assets/app.4bd937d4.js:1:56875)
```

### System Info

```shell
System:
  OS: Windows 10 10.0.19044
  CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
  Memory: 1.59 GB / 7.92 GB
Binaries:
  Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.62)
  Internet Explorer: 11.0.19041.1566
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
> begin with special char

No, is actually when heading "only" has special characters 😅.

**Comment by xfq** [comment]
One way to fix this is to generate IDs using the hash of the section's content (like [Bikeshed](https://github.com/tabatkins/bikeshed/blob/f1c9d5eb99c9e633f56fffc6cd43143b7533f6eb/bikeshed/unsortedJunk.py#L1012) does), so that the generated ID is relatively stable.

Another way is to use something like `generateID-1`, but if a new section is inserted before this section, the id of this section will change.

**Comment by yyx990803** [comment]
The fixed should be applied [here](https://github.com/mdit-vue/mdit-vue/blob/main/packages/shared/src/slugify.ts) - it's the slugify function used in VitePress. We should add a valid leading char if it is not after all the transforms.

/cc @meteorlxy

**Comment by posva** [comment]
I think a better fix would be to use `document.getElementById()` instead of `querySelector()` as a hash always refers to an id and it's always unique in the page. `getElementById()` supports more characters like `$` that are used in titles for properties (especially in API docs) or even numbers so [replacements like this in mdit-vue](https://github.com/mdit-vue/mdit-vue/blob/main/packages/shared/src/slugify.ts#L23) are not necessary

This will fix many issues with API docs for Router and Pinia

- https://github.com/vuejs/pinia/pull/2292

**Comment by meteorlxy** [comment]
Sorry for delay. I ignored the message. I'll check the default slugify function.

@posva What you suggested seems not the same issue. Maybe you can create another issue for that.

**Comment by posva** [comment]
What I'm saying is that `#-7` or `#3` is a valid id. In more real scenarios `$pinia` is a valid title but the problem doesn't come from mdit-vue, in fact, it should **not** escape those characters. Instead, vitepress should use getElementbyId to find the elements

**Comment by meteorlxy** [comment]
I see. I just checked the spec and found the root cause.

Per [HTML5 spec](https://html.spec.whatwg.org/#the-id-attribute), id can consist of just punctuation, so the id generated by mdit-vue should be valid.

<img width="1322" alt="image" src="https://github.com/vuejs/vitepress/assets/18205362/32c313ed-b0b1-408b-b4b4-d5e318464268">

The `querySelector()` accepts CSS selectors. Per [CSS spec](https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier), IDs do not allow special chars:

<img width="1779" alt="image" src="https://github.com/vuejs/vitepress/assets/18205362/3f3655ef-1f8e-4310-9978-255fa81e3ee7">

Thus, what you suggested should be the correct solution @posva 👍

**Comment by ByMykel** [comment]
Special characters don't allow sroll down when I open links like the one below. Is it only happening to me?

https://pinia.vuejs.org/api/interfaces/pinia._StoreWithState.html#Methods-$patch

**Comment by posva** [comment]
It's because it uses querySelector() instead of getElementById @ByMykel . That should work in the next version of vitepress
