### ISSUE TITLE
Just created vuepress-next prototype before noticed this project

### ISSUE THREAD

**Issue by meteorlxy** [vuejs/vitepress#13]
As a member of current vuepress team, I just created a prototype for vuepress next major version: https://github.com/vuepress/vuepress-next

- Vue 3 ecosystem
- Typescript
- Drop class API, use compositional functions
- Try do decouple with webpack, may support different bundlers (e.g. vite)

Today I noticed vitepress and don't know where to go next 😢 

@yyx990803 Could you please give some advice?

**Comment by yyx990803** [comment]
I think VitePress ticks most of these boxes and more... so it's an unfortunate coincidence - but honestly, I don't think a VuePress next is needed.

**Comment by meteorlxy** [comment]
I see. Will vitepress accept collaborators, or it'll maintained by yourself?

**Comment by meteorlxy** [comment]
@yyx990803   Will VitePress accept collaborators, or it'll be maintained by yourself?

I hope to help build VitePress together with my experience of VuePress

**Comment by meteorlxy** [comment]
Another question, as vitepress is lighter-weighted, and vuepress is more flexible, if vuepress cannot be fully replaced by vitepress, will they be maintained in parallel?

**Comment by yyx990803** [comment]
@meteorlxy now looking back at it, I think the whole idea of plugins in VuePress was a bit of over-engineering. Many of the things the plugins are doing can be done simply in `enhanceApp` of a theme. There is a chance to greatly simply the concept in general.

VuePress will and should be maintained, of course, until VitePress proves to be able to replace it.

**Comment by rexwangcc** [comment]
> @meteorlxy now looking back at it, I think the whole idea of plugins in VuePress was a bit of over-engineering. Many of the things the plugins are doing can be done simply in `enhanceApp` of a theme. There is a chance to greatly simply the concept in general.
> 
> VuePress will and should be maintained, of course, until VitePress proves to be able to replace it.

Sorry to comment on a closed issue, as an frontend **amateur**, may I ask how removing the plugin system could impact the Vuepress (or VitePress) ecosystem, especially from the code-sharing/re-usability perspective? One of the features I enjoyed as an user of vuepress is that I can plug-and-play a variety of plugins by just installing them and list them in the `config.js` without having to worry about customizing the themes (which are a bit heavy to me). 

In general, I'm not sure what does it look like if we have to be bound to a single theme only because we need a small part of its features/components. That said, VitePress does seem to solve the speed problem which bothers a lot of Vuepress users who have thousands of pages, so I'd like to migrate asap :)
