### ISSUE TITLE
build failed with webworker?

### ISSUE THREAD

**Issue by edgexie** [vuejs/vitepress#1438]
### Is your feature request related to a problem? Please describe.

I use a lib named `@antv/l7`, the lib is used `webworker`, so when I run build，there is a error `self is not defined`. see the error in the [actions](https://github.com/edgexie/edgexie.github.io/actions/runs/3193642160/jobs/5212410104)
![image](https://user-images.githubusercontent.com/18474752/194188266-09b85af8-5fee-484b-ac8a-06d9d55150c3.png)

### Describe the solution you'd like

build pass and describe how to use webworker in vitepress in the offical doc.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by kiaking** [comment]
Maybe it' node issue? Can you try wrapping the code in `<ClientOnly>` component and see what happens? 👀

**Comment by edgexie** [comment]
> Maybe it' node issue? Can you try wrapping the code in `<ClientOnly>` component and see what happens? 👀

I have allready code `<ClientOnly>`，but get the same result. The script is at the [link - click me](https://github.com/edgexie/edgexie.github.io/edit/master/docs/about-me.md)

![image](https://user-images.githubusercontent.com/18474752/199244282-bb1891b7-2c8f-4445-a038-2a335e047909.png)

**Comment by brc-dd** [comment]
The error is probably because that library too isn't friendly with server (has some side-effects or using browser/worker APIs while being imported). Use dynamic import to handle that: https://vitepress.dev/guide/ssr-compat#libraries-that-access-browser-api-on-import

Also, check if it works in dev (dynamic import, client only, etc. doesn't matter in dev). If it doesn't there is something wrong with that library not vite or vitepress itself.
