### ISSUE TITLE
$title compat with vuepress

### ISSUE THREAD

**Issue by matias-capeletto** [vuejs/vitepress#158]
@kiaking when working on https://github.com/vuejs/vitepress/pull/152, I assumed that it was the title that appeared in the sidebar links:
```
$title = $page.title || $site.title
```

But reviewing [the code in Vuepress](https://github.com/vuejs/vuepress/blob/fbf5e5d99b40e3842a0a2566f9eb35e05863eab5/packages/%40vuepress/core/lib/node/ClientComputedMixin.js#L78), it looks like it is actually the title of the document:
```
$title = ( $page.title ? $page.title + ' | ' + $site.title ) : $site.title
```

I think it is more useful as we have it (and maybe add a $documentTitle), but maybe we need to align it to vuepress and have:
```
$title <- same as in vuepress
$sidebarTitle <- current one (or we do not expose this one at all)
```

It will be an interesting walk to keep as much of compat with vuepress but take the opportunity to break what could be improved. I am fine with both options here.

Thoughts?

**Comment by kiaking** [comment]
Ah, nice catch. I think we should align with VuePress about this one. Since `$description` is getting the actual `description` for the site, we should do same with the `$title` too.

But I understand the pain. How about making `$page.title` always exist as you mentioned in another issue. So page title becomes:

```js
infertTitle(page.title) || siteDataByRoute.title
```

Since it's essential for pages to have title so 😳

**Comment by matias-capeletto** [comment]
I agree with both.

I'll send a PR 👍

**Comment by kiaking** [comment]
Wonderful! 🙌
