### ISSUE TITLE
No line splitting in Code Blocks

### ISSUE THREAD

**Issue by Goozoon** [vuejs/vitepress#1697]
### Describe the bug

When we have long lines within a Code block, lines do not split into multiple lines
<img width="254" alt="image" src="https://user-images.githubusercontent.com/48757340/207985200-49a9dff9-339c-45c1-8b56-798689266f35.png">

Also, if the first line is long enough it got interfered with upper right language name
<img width="92" alt="image" src="https://user-images.githubusercontent.com/48757340/207985142-5c825804-785c-4120-aebd-a232b3ed64cc.png">

### Reproduction

For Example:

```sql
DECLARE @pathNameDB NVARCHAR(512) 

SET @pathNameDB = 'D:\Backup\DBServerName_' + Convert(varchar(8), GETDATE(), 112) + '.bak' 
BACKUP DATABASE [DataBaseName] TO DISK = @pathNameDB WITH NOFORMAT, NOINIT, NAME = N'db_backup', SKIP, NOREWIND, NOUNLOAD, STATS = 10

GO
```

### Expected behavior

Line splitted, so reader dont need to use scroll bars to see the whole line

### System Info

```shell
windows, alpha31
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by kiaking** [comment]
> When we have long lines within a Code block, lines do not split into multiple lines

This is expected. In Code Block, line should not wrap automatically. Same as GitHub you know. Like 👇 

```bash
Super long long long long long text text text long long long long long text text textlong long long long long text text textlong long long long long text text textlong long long long long text text text
```

You should format the code so that users can easily read it. Auto wrapped code is usually hard read than not wrapped code.

```
DECLARE @pathNameDB NVARCHAR(512) 

SET @pathNameDB = 'D:\Backup\DBServerName_' +
                  Convert(varchar(8), GETDATE(), 112) + '.bak'

BACKUP DATABASE [DataBaseName]
  TO DISK = @pathNameDB
  WITH
    NOFORMAT,
    NOINIT,
    NAME = N'db_backup',
    SKIP,
    NOREWIND,
    NOUNLOAD,
    STATS = 10

GO
```

> Also, if the first line is long enough it got interfered with upper right language name

This is good point, but very hard to fix. Because if we were to increase the box size, it gets too big on usual not long single line code block.

I think this should be left for document author to come up with some good best practice. For example, if you do have very long code example, maybe it would make sense to add comment on the first line to avoid it hitting the language name.

```bash
# Add this kind of comment.
$ then write long text long text long text long text long text long text long text long text long text long text long text long text
```
