### ISSUE TITLE
How to configure the build directory of vitepress ?

### ISSUE THREAD

**Issue by soulsam480** [vuejs/vitepress#171]

**Comment by loonpwn** [comment]
You can't at the moment, `dist` in the `.vitepress` folder is hardcoded.

**Comment by soulsam480** [comment]
Sure

**Comment by Jaimeloeuf** [comment]
Hi @harlan-zw just curious if there is a reason why this is not supported in vitepress unlike vuepress? Does not necessarily seems like a difficult thing to do unless I missed something?

Having this config would be great where a vitepress site's source files and build output can be in the same github repo and use github pages for hosting, unlike the solution in the [docs](https://vitepress.vuejs.org/guide/deploy.html#github-pages) which requires another repo just for the output.

If this is something that is reasonable, let me know and perhaps I can submit a PR? Thanks!

**Comment by harlan-zw** [comment]
Hey @Jaimeloeuf, this is a pretty outdated issue and I haven't touched vitepress too much since it was raised. 

Having a quick glance at the code though, it seems like there is now a `outDir` option that should let you control it, but I'm not too sure. 

https://github.com/vuejs/vitepress/blob/main/src/node/config.ts#L69

**Comment by Jaimeloeuf** [comment]
Hey @harlan-zw thanks alot for getting back to me on this old issue!

Looking through the code, although there is a `outDir` prop on the `SiteConfig` interface since quite a few commits back, it looks to be always hard coded to be 'dist' and nothing else.<https://github.com/vuejs/vitepress/blob/6085501acbfcc122f42fef8000b7abc7f4cecc92/src/node/config.ts#L118> 

---

Also the other thing I noticed is that this prop is on the `SiteConfig` interface, and not the `UserConfig` interface [here](https://github.com/vuejs/vitepress/blob/6085501acbfcc122f42fef8000b7abc7f4cecc92/src/node/config.ts#L24) which from what I understand looking at the code, the `UserConfig` is designed to override some `SiteConfig` props but just that the `outDir` prop in particular is left out.

Since the `resolveConfig` function always return the hardcoded `outDir`, there is currently no way to override it other than manually editing the config.ts file or maintaining a fork which I would like to avoid. Do you think that this feature is something that can be added? And if so, I would be able to help out with a PR.

Let me know, thanks a lot!

**Comment by harlan-zw** [comment]
Nice investigating @Jaimeloeuf 

I know that VitePress aims to be simple and opinionated in how it's built, saying that it seems like a useful feature and can't imagine it would be _that_ much work. I don't have much control over what will and won't get merged but submitting a PR seems like a good idea if you have some time to work on it.

**Comment by Mando75** [comment]
Hi, I have opened a PR to add this option to the UserConfig. Please see #448 and leave any feedback you have. Hopefully the maintainers see the value and decide to add it.

**Comment by Jaimeloeuf** [comment]
Hey @Mando75 thanks alot for the help! Got abit busy and appreciate it, hope this gets merged soon :)

**Comment by Mando75** [comment]
FYI, my PR was merged, so you can now set the output directory by using the `outDir` parameter in your vite config.
