### ISSUE TITLE
使用中文时 斜体不起作用

### ISSUE THREAD

**Issue by whylost** [vuejs/vitepress#2036]
### Describe the bug

使用中文时 斜体不起作用

例如  *我是文字*

![image](https://user-images.githubusercontent.com/62528887/222915313-8c379ed3-a50f-4181-8905-17751276ab41.png)

### Reproduction

No Reproduction

### Expected behavior

*汉字* 显示斜体

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 15.46 GB / 23.88 GB
  Binaries:
    Node: 18.14.2 - D:\SoftWare\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.0 - D:\SoftWare\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.63), ChromiumDev (111.0.1661.27)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitepress: 1.0.0-alpha.49 => 1.0.0-alpha.49
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by godxiaoji** [comment]
It is caused by using `system-ui`.

related: https://github.com/vuejs/vitepress/pull/1162

**Comment by kiaking** [comment]
Any recommendation on what font family we should specify for Chinese?

**Comment by Jinjiang** [comment]
试一下这里的样式
https://github.com/vuejs-translations/docs-zh-cn/blob/main/.vitepress/theme/styles/zh-cn.css
相关讨论
https://github.com/vuejs-translations/docs-zh-cn/pull/574/files
谢谢

**Comment by brc-dd** [comment]
For me, the current styles are working fine on Chrome, but not on Firefox and Safari 👀  (but yeah IG its synthesizing styles because I don't think if Inter has Chinese glyphs. For me none of my system fonts are supporting italics on Firefox)

<img width="214" alt="image" src="https://user-images.githubusercontent.com/40380293/224317339-bc95c21e-3821-4938-808f-55a98acb78eb.png">

Firefox (doesn't work even with the styles @Jinjiang  suggested):

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/40380293/224317148-59cd5744-b01f-48a8-9a66-238a93a117a8.png">
