### ISSUE TITLE
Using Vitepress and Element Plus at the same time and building with Yarn will fail.

### ISSUE THREAD

**Issue by StreakingMan** [vuejs/vitepress#2255]
### Describe the bug

Since after vitepress@1.0.0-alpha.66 has update vueuse to v10.x, while elment-plus@2.3.3 still using vueuse@9.x, build will fail like that:

```
file:///home/projects/vite-prhpmo/docs/.vitepress/.temp/app.js:3
import { isClient, isNumber, useEventListener, useThrottleFn, useMediaQuery, useWindowScroll } from "@vueuse/core";
                   ^^^^^^^^
SyntaxError: The requested module '@vueuse/core' does not provide an export named 'isNumber'
    at async ModuleJob.run (https://viteprhpmo-pjkg.w-credentialless.staticblitz.com/blitz.c8358679.js:35:1077745)
    at async Promise.all (index 0)
    at async ESMLoader.import (https://viteprhpmo-pjkg.w-credentialless.staticblitz.com/blitz.c8358679.js:35:1312625)
    at async Module.build (file://file:///home/projects/vite-prhpmo/node_modules/vitepress/dist/node/serve-4d1b4005.js:41686:24)
```

IsNumber was removed in vueuse v10.x. what generated in `.temp/app.js`  since didn't solve the different version of vueuse.

At that moment I was using yarn v1.x, and then I change to npm, after reinstall, it build success.

I'm not sure it was the problem of pakage manager or vite/vitepress, or element-plus, or something else...

And this issue #2187 may be related.

### Reproduction

Here is two Reproduction:

with yarn, build failed:
[https://stackblitz.com/edit/vite-prhpmo?file=docs/.vitepress/config.ts
](https://stackblitz.com/edit/vite-prhpmo?file=docs/.vitepress/config.ts
)

with npm, build success:
[https://stackblitz.com/edit/vite-wwmku1?file=docs/.vitepress/config.ts](https://stackblitz.com/edit/vite-wwmku1?file=docs/.vitepress/config.ts)

with pnpm build success too.

what I found is that on the root of node_modules folder, yarn install vueuse@10.x while other package manager install v9.x

### Expected behavior

Build success while using yarn.

### System Info

```shell
Just see stackblitz demo.
```

### Additional context

yarn
![image](https://user-images.githubusercontent.com/30397306/232771356-4488bf8b-2d77-4188-bdbe-3087723b592c.png)

npm
![image](https://user-images.githubusercontent.com/30397306/232771489-0da4d9d7-a67d-4871-adef-7f579f0898dd.png)

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
npm is probably doing some weird hoisting thing that's why it's working.

The issue though isn't of vitepress or element plus or even the package manager. The issue is with using them all together. It can be made to work (in this particular case) by just adding `@vueuse/core@^9` as dep.

But that too isn't a robust resolution, it works because we aren't using any function from vueuse that has changed between v9 and v10. If we had then both of those package manager would have failed.

In general hold off upgrading a dependency if other has conflicting versions. Or better use pnpm. It isolates the deps. Although you might end up with two versions of same dep in the app.
