### ISSUE TITLE
allow using path aliases in data loader files

### ISSUE THREAD

**Issue by brc-dd** [vuejs/vitepress#2289]
### Discussed in https://github.com/vuejs/vitepress/discussions/2279

<div type='discussions-op-text'>

<sup>Originally posted by **said-m** April 24, 2023</sup>
Hi, i need your help to solve the problem… getting an error when ts path alias resolves from `*.data.ts` files.
Here an example: https://stackblitz.com/edit/vite-j8rvru?file=docs/blog/posts.data.ts

* `constants.ts`
* `**/helper.ts` - it has import with path alias: `~/constants`
* `**/some.md` - imports `./helper` and everything is ok
* `**/some.data.ts` - imports `./helper` and it fails

is it an issue or am i doing something wrong in the configuration?</div>

**Comment by pavelhoral** [comment]
Just spent two days on this issue... I might have more minimalistic example https://stackblitz.com/edit/vite-xgbzgm?file=docs%2F.vitepress%2Fconfig.ts .

**Comment by pavelhoral** [comment]
I thought I would be able to help with this issue but it my skill level seems to be too low for that. I am not even sure there is a solution...

If I understand it correctly, [this is the place](https://github.com/vitejs/vite/blob/dcee6ef08e98548eea262695249134ab7ada0302/packages/vite/src/node/config.ts#L1042) where the resolution process happens. If there is a way how this method can resolve aliases, it must be hidden a few levels deeper. Maybe a proper solution would be to not use [`loadConfigFromFile`](https://vitejs.dev/guide/api-javascript.html#loadconfigfromfile).

A potential workaround might be to use NPM workspaces so that there is no need for aliases and imports are really proper package imports. In that way Node-based resolver should be able to resolve that.

Or actually much simpler workaround - just use non-aliased relative path imports :)

**Comment by brc-dd** [comment]
Yeah, `loadConfigFromFIle` won't work. In order to handle aliases, it'd need to pass through vite pipeline. I'm still unsure how we can do that from inside plugins. I was thinking to use jiti or esbuild directly for importing those files. But both of those don't support alias format similar to vite.

Edit: track with #3125
