### ISSUE TITLE
Nginx deployment, refresh the browser page content display problem

### ISSUE THREAD

**Issue by wulianpu** [vuejs/vitepress#2342]
### Describe the bug

After I deploy VitePress to Nginx, refreshing the page will display both the content of the home page and the content of the current route, Why does this happen
![image](https://user-images.githubusercontent.com/44516614/236496960-15ecf727-6e17-4138-998e-30f463d0e81b.png)

nginx configuration：
~~~
location /docs {
      alias /Users/wulianpu/Workplace/vitepress/docs/.vitepress/dist;
      try_files $uri $uri/ /docs/index.html;
}

**Comment by brc-dd** [comment]
Have you set `base: '/docs/'` in `.vitepress/config.ts`?

**Comment by gyhyfj** [comment]
If I navigate from a 404 page to other page, the 404 page's content will stay at the top of existing article.
Another problem relatived is that if I put one svg in `ClientOnly` componet of home page's slot, if I toggle pages between home page and other pages, that svg element will be more and more .
Everything works well if just run dev instead of run build. I will give one minimal reproduction tomorrow.

**Comment by wulianpu** [comment]
> 你设置了吗？也尝试在 vitepress 配置中禁用。`base: '/docs/'``.vitepress/config.ts``cleanUrls`

According to your method, it's feasible. Thank you very much
