### ISSUE TITLE
Introduction custom container

### ISSUE THREAD

**Issue by Dschungelabenteuer** [vuejs/vitepress#2473]
### Is your feature request related to a problem? Please describe.

When I write documentation, I sometimes want to have some sort of introductory paragraph to set some context for the readers. These kinds of introductory paragraphs are often visually emphasized to catch attention and get even more impactful. Usually, the emphasis relies on styling (e.g. bigger font size, bolder font weights, etc).

I really think it would be convenient for many users to be able to specify introductions in a straight-forward and _markdownish_ way, so that such content gets emphasized through styling while preserving other markdown rules and features .

### Describe the solution you'd like

To address this need, we basically want to take a whole identified block and apply some styles to make it stand out. It turns out this kind of feature already exists in Vitepress: [custom containers](https://vitepress.dev/guide/markdown#custom-containers). These perfectly match our needs because:
- they can be clearly identified because the syntax really pops out
- their content still benefit from markdown syntax
- they contextually provide their content a special, highlighted role

My belief is that it makes sense to also provide a `intro` custom container because those share a common philosophy. However, there is a slight difference : unlike other custom containers, I feel like it does not make any sense for `intro`s to include default and custom titles because well… they're introductions).

### Describe alternatives you've considered

I used to work this around by explicitly wrapping my introductory paragraph with a `<p class="intro"></p>` block, and defining some CSS on the `.intro` selector, since it is supported.  This works just fine, but being in a explicit HTML block prevents me from benefiting from other markdown features. For example, this would not work as expected:

```md
<p class="intro">
   [click me](https://github.com)
</p>
```` 

### Additional context

I've came up with the following draft PR: #2474. It's marked as draft because [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md) state that we "should open a suggestion issue first ", but could not resist to give it a try.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
I'm not quite inclined towards having this in the default theme. I've several reasons:

- This can be added directly via vitepress config if someone needs it (refer https://vitepress.dev/guide/markdown#advanced-configuration, https://github.com/markdown-it/markdown-it-container).
- I'm yet to see any significant demand for such a component. If there is much demand, we can consider adding it.
- Your alternatives part is not working because you don't have empty space between markdown and html. Something like this would work (refer https://spec.commonmark.org/0.30/#html-blocks):
    
    ```md
    <p class="intro">
    
    [click me](https://github.com)
    
    </p>
    ```

**Comment by Dschungelabenteuer** [comment]
Hey @brc-dd! Thank you so much for taking the time to review this feature request, really appreciated! (and sorry for taking that much time to address your feedback). These reasons you gave definitely make sense!

I'd just like to argue on that last point regarding the CommonMark specifications. I'm far from being an expert in that matter, but I am aware of these blank lines requirements. However, it seems like writing down the alternative you've described would end up being compiled as the following:

```html
<p class="intro"></p><p><a href="https://github.com" target="_blank" rel="noreferrer">click me</a></p>
```

Which, you've probably guessed it, is not quite the behaviour I'm expecting! Once again, I'm not an expert so I might be missing something else. Still, I do understand your points, and I'll therefore address this by customizing my Vitepress' config as you suggested  :-)  Please let me know if you want me to close this issue, or if you'd rather keep it open for further reference! Thanks!

**Comment by brc-dd** [comment]
Ah, that's happening because of `p` can't be nested inside another `p` tag. So, "any `<p>` (or other block-level element) will implicitly close any open `<p>`." You can use a div instead to make it work:

```md
<div class="intro">

[click me](https://github.com)

</div>
```

https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%3Cdiv%20class%3D%5C%22intro%5C%22%3E%5Cn%5Cn%5Bclick%20me%5D%28https%3A%2F%2Fgithub.com%29%5Cn%3C%2Fdiv%3E%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Atrue%2C%22_view%22%3A%22html%22%7D%7D
