### ISSUE TITLE
nav actived item error

### ISSUE THREAD

**Issue by xiaoxintang** [vuejs/vitepress#259]
**Describe the bug**

there are two url link`/frontend/javaScript`&`/frontend/javaScriptDesign`,when i choose `/frontend/javaScriptDesign`,the `/frontend/javaScript` item is actived too

![image](https://user-images.githubusercontent.com/24927686/110412170-b4cac680-80c6-11eb-8250-23f28949504a.png)

**Expected behavior**

**System Info**
- vitepress version:  0.12.2
- vite version:
- Node version: 14.15.4
- OS version: macos 11.2.1 (20D74)

**Additional context**

```js
{
    text: "前端",
    items: [
	    {text: 'js', link: '/frontend/javaScript'},
	    {text: 'js设计模式', link: '/frontend/javaScriptDesign'},
	    {text: '兼容性', link: '/frontend/compatible'},
	    {text: '框架', link: '/frontend/frame'},
	    {text: '性能', link: '/frontend/performance'},
	    {text: '视频', link: '/frontend/video'},
	    {text: 'css', link: '/frontend/css'},
	    {text: '浏览器', link: '/frontend/browser'},
    ]
}
```

**Comment by Zelig880** [comment]
I have done some quick initial investigation and noticed that the issue is not actually related to the `isActive` utility, but is actually due to the wrong relative pass being passed as part of the page data.

Please see the following screenshot. The URL is `/guide/javaScriptDesign.html` but the relative path is: "guide/javaScript.md". This is resulting in a bad active link being displayed:

<img width="1679" alt="Screenshot 2022-06-26 at 23 14 31" src="https://user-images.githubusercontent.com/9040770/175835819-58eeb470-b11e-49bc-bd87-14818c88b790.png">

**Comment by brc-dd** [comment]
Can anyone share a reproducible example for this? I am not able to reproduce this.
