### ISSUE TITLE
feat: changeable entry file

### ISSUE THREAD

**Issue by privatenumber** [vuejs/vitepress#280]
**Is your feature request related to a problem? Please describe.**

Vitepress defaults to `index.md` as the entry file. GitHub defaults to `README.md`/`readme.md` as the entry file for the directory, and I would like my repo and site to be consistent.

**Describe the solution you'd like**
An `entry` config that defaults to `index.md` but can be changed to `readme.md`

**Describe alternatives you've considered**

**Additional context**

**Comment by kiaking** [comment]
Interesting. So you wanna make the docs readable in both on GitHub and on deployed site right...? That makes sense.

**Comment by privatenumber** [comment]
Yeah, they would both be readable anyway, but I want the entry points to be consistent.

Also, the default entry point in Vuepress is `README.md` so supporting this also offers a smoother migration path.

**Comment by rickalex21** [comment]
@privatenumber I think both are supported in vuepress but not in vitepress, I may be wrong here. I know I have both working in vuepress.

**Comment by sigtm** [comment]
Would love this feature. In our case, it's not actually about `/docs` being readable in the actual site repo – large sections of our docs are automatically pulled from other repos when they have new releases. And those repos use `README.md` as the entry points, since they need to be readable on GitHub, independently of the main docs site. Which works great with Vuepress, but now hoping to migrate to Vitepress.

**Comment by Bukunmikuti** [comment]
I was about filing a bug report for this. 
I believe this should be the expected behaviour as it allows for consistency.
