### ISSUE TITLE
Customize the code blocks of the md file

### ISSUE THREAD

**Issue by TomokiMiyauci** [vuejs/vitepress#313]
I wanted to write my own markdown-it plugin and use own custom syntax for code blocks.

For example, include the file name in the code block:
\`\`\`ts[main.ts]
\`\`\`

However, the language detection logic of `highlightLinePlugin` seems to allow only`/{([\d,-]+)}/`, which is the notation of` lineNumberPlugin`.
https://github.com/vuejs/vitepress/blob/master/src/node/markdown/plugins/highlightLines.ts#L4

Is this a deliberate constraint?

**Comment by brc-dd** [comment]
You can write a plugin using `markdown-it-container` instead and have code like this:

```md
::: ts[main.ts]
:::
```

Let us know what exactly you are trying to accomplish by your plugin. Someone from the community might be of assistance then.

**Comment by brc-dd** [comment]
Here is a quick demo of how you can write a plugin to display file name along with the code:

```js
// .vitepress/config.js

import Container from 'markdown-it-container'

const codeRE = /^code\s+(.*)$/

export default {
  markdown: {
    config: (md) => {
      md.use(Container, 'code', {
        validate: (params) => params.trim().match(codeRE),
        render: (tokens, idx) => {
          const m = tokens[idx].info.trim().match(codeRE)
          if (tokens[idx].nesting === 1)
            return `<div><div class="code-file">${m[1]}</div>`
          else return '</div>\n'
        }
      })
    }
  }
}
```

Markdown Code:

````md
# Demo

Codeblock with file name:

::: code main.ts

```ts
// do this inside your main.ts file
export default {}
```

:::
````

Rendered Output:

![image](https://user-images.githubusercontent.com/40380293/172057469-eff2af3f-1ad0-4265-ae5c-2c14209c3e77.png)

However I believe that this can be better done with a Vue component instead of a md one.
