### ISSUE TITLE
 XXX is not supported resolving ES modules imported from XXX

### ISSUE THREAD

**Issue by nextroado** [vuejs/vitepress#3425]
### Describe the bug

There is no problem in the development environment, but an error was thrown during packaging execution
<img width="1320" alt="image" src="https://github.com/vuejs/vitepress/assets/142566415/3a33fbd2-7d53-4bee-b0d0-db8ded2b047d">

### Reproduction

For development - npm run docs:dev
For build - npm run docs:build

Equivalent stackblitz links:
[https://stackblitz.com/edit/vite-dkrbry](https://stackblitz.com/edit/vite-dkrbry)

### Expected behavior

Production should match with development.

### System Info

```Text
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
  npmPackages:
    vitepress: latest => 1.0.0-rc.35
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Seems like an issue with that library. It's either bundling things wrong or is not compatible with vue 3.

**Comment by nextroado** [comment]
@brc-dd There are no issues with this library in Vite
[https://stackblitz.com/edit/vitejs-vite-zznnss](https://stackblitz.com/edit/vitejs-vite-zznnss)

**Comment by brc-dd** [comment]
> There are no issues with this library in Vite

That doesn't mean it's not broken. It is shipping invalid ESM which doesn't work with node properly, for example:

```js
// devextreme-vue/esm/button.js

import { createComponent } from "./core/index";
```

This is invalid because node does not permit directory or extension-less imports. There are many similar cases. Also, all the package.json are wrong there. They are resolving to CJS builds. You can force vite to transpile all these by doing something like in your `.vitepress/config.ts`

```ts
  vite: {
    plugins: [MarkdownPreview()],
    ssr: {
      noExternal: ['devextreme', 'devextreme-vue', '@devextreme/runtime'],
    },
  },
```

**Comment by brc-dd** [comment]
> There are no issues with this library in Vite

That doesn't mean it's not broken. You can force vite to transpile the deps by doing something like this in your `.vitepress/config.ts`:

```ts
  vite: {
    // ...
    ssr: {
      noExternal: ['devextreme', 'devextreme-vue', '@devextreme/runtime'],
    },
  },
```

It still will log some warnings in terminal due to unused imports and esm interop. But should work fine in runtime.

The long term solution however is to fix this at the source is ship valid ESM and exports map in package.json, or switch to Bun which does all of this at runtime level.

PS: I think the ESM is valid, just the esm files need .mjs extension.
