### ISSUE TITLE
History back issue while using iOS Safari

### ISSUE THREAD

**Issue by isishome** [vuejs/vitepress#3658]
### Describe the bug

When using iOS Safari, if you move to the actions link on the home page and then swipe history back, clicking on the elements on the home page is interrupted once.
Works fine from the second touch.

### Reproduction

home > click action button > swipe history back > click action button

### Expected behavior

No response to action button on home page after history back.

### System Info

```Text
iPhone SE2 (2020)
iOS 17.4
safari
```

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by gwansikk** [comment]
I delved into this bug out of curiosity.

- The swipe-back feature works fine on macOS Safari.
- However, the issue arises on iOS and iPadOS Safari.
- I observed that the swipe-back behaves differently on iOS and iPadOS.

In essence, the swipe-back on mobile devices uniquely engages the `back-forward cache*`, leading to a situation where the cache is retrieved and rendered, but JavaScript does not execute.

I have found a solution to this issue but am researching for a potentially better approach.

Additionally, I plan to investigate and address the following

- Whether this bug is replicated in other versions of Safari
- Consulting Apple's developer documentation for a superior solution
- Understanding why this issue is exclusive to mobile Safari

Would it be okay to submit a PR once all these points are thoroughly examined?

Thanks!

*It's noted that this cache differs from the standard caching as it only caches the HTML code.

**Comment by brc-dd** [comment]
Yeah PRs are welcome. But I'm not seeing this issue with https://vuejs.org/, what are we doing different here than theme 👀

**Comment by 0xlau** [comment]
> Yeah PRs are welcome. But I'm not seeing this issue with https://vuejs.org/, what are we doing different here (other than theme) 👀

This information is crucial. 😄

I checked the docs repository on the official website of Vuejs.org and found that they are using version rc.33, which is a breakthrough point for this issue.

I tried to fix it and submit a PR #3671 .
