### ISSUE TITLE
VitePress fails to start with @vitejs/plugin-vue in Vite config

### ISSUE THREAD

**Issue by chengbotao** [vuejs/vitepress#4442]
### Describe the bug

When I integrate VitePress into a Vue + TypeScript project created with Vite, VitePress fails to start if the @vitejs/plugin-vue plugin is included in the plugins array of vite.config.ts. However, VitePress starts successfully if I remove the @vitejs/plugin-vue plugin from the configuration.

### Reproduction

1. Create a Vue + TypeScript project using Vite.
2. Integrate VitePress into the project.
3. Include @vitejs/plugin-vue in the plugins array of vite.config.ts.
4. Attempt to start VitePress, which results in an error and prevents it from starting.
5. Remove @vitejs/plugin-vue from vite.config.ts.
6. VitePress starts successfully without the plugin.

### Expected behavior

VitePress should be able to start without any issues even with @vitejs/plugin-vue included in the vite.config.ts configuration.

### System Info

```Text
Node.js 版本：18.16.1
npm/yarn/pnpm 版本：pnpm-9.2.0
Vite 版本：6.0.5
VitePress 版本：1.5.0
操作系统：macOS Sequoia 15.2
```

### Additional context

![image](https://github.com/user-attachments/assets/149556ba-d2e3-4ed9-a18f-dcde9ba53b8f)

[stackblitz demo](https://stackblitz.com/edit/vitejs-vite-ykugpvjm?file=README.md)

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
This is because vitepress adds that plugin by default, duplicating it in the chain. You can add this to .vitepress/config.ts

```ts
  vite: {
    configFile: false
  }
```

It will disable vite.config.ts auto-discovery when running vitepress. You'll need to copy any additional vite settings (except vue plugin) in .vitepress/config.ts too.

Alternatively you can configure a different root for vitepress (i.e. keep it inside docs/ or something instead of using cwd as root for both your vite app and docs).

**Comment by chengbotao** [comment]
Your reply has resolved my issue, thank you very much.
