### ISSUE TITLE
Release's appear to not be updating

### ISSUE THREAD

**Issue by CodyBontecou** [vuejs/vitepress#510]
### Describe the bug

@yyx990803's commit messages tend to have release numbers. 
<img width="877" alt="Screen Shot 2022-01-26 at 18 56 51" src="https://user-images.githubusercontent.com/20440899/151294591-3fced60a-001d-4072-8c2d-69748dc550e6.png">

I noticed they aren't hooked up to Github's release UI.
<img width="266" alt="Screen Shot 2022-01-26 at 18 56 57" src="https://user-images.githubusercontent.com/20440899/151294588-b0f511cd-8f36-4623-9833-0b34766704e2.png">

### Reproduction

Viewable on the main page of the repo.

### Expected behavior

Release information should be updated and viewable within the Github release interface.

### System Info

```shell
N/A
```

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/coc)
- [X] Read the [docs](https://vitepress.vuejs.org/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by brc-dd** [comment]
Actually the [current release workflow](https://github.com/vuejs/vitepress/blob/45b65ce8b63bd54f345bfc3383eb2416b6769dc9/scripts/release.js) used by the VitePress team just [tags](https://github.com/vuejs/vitepress/tags) the versions and doesn't actually release them on GitHub.

To the members: You guys can use [`release-it`](https://github.com/release-it/release-it) instead of a custom script. It has support for all these things.

**Comment by yyx990803** [comment]
It's automated now via 9f2d361
