### ISSUE TITLE
Configure for multi-page applications

### ISSUE THREAD

**Issue by gagayang** [vuejs/vitepress#57]
尤大： 
请问如何配置一个多页面的、使用不同layout 布局的应用呢？？

**Comment by kiaking** [comment]
@antfu Please help me out here (with the language 😅 )

**Comment by antfu** [comment]
Translation:
```
Evan:
How to configure a multi-page application that uses different layouts? ?
```

**Comment by kiaking** [comment]
Thanks antfu for the translation!

So the answer is currently, you can not. Well we can do pretty much anything in `.vitepress/theme/Layout.vue` so we could just add condition depending on the `SiteData` to do this I guess?

Since VitePress is **opinionated** version of VuePress (at least at the moment), not sure if we want to support this in for example config. Let's keep this issue open for maybe a week or so to gather more feedbacks.

**Comment by bowencool** [comment]
Adding html entry doesn't work
``` ts
// docs/vite.config.js
export default defineConfig({
  ...
  build: {
    rollupOptions: {
      input: {
        // main: resolve(__dirname, 'index.html'),
        demos: resolve(__dirname, 'demos.html'),
      },
    },
  },
});
```
![image](https://user-images.githubusercontent.com/20217146/142593193-73c301b8-e1b4-4cb6-83a5-e6aba9ec3967.png)

**Comment by yyx990803** [comment]
1. 写自定义的 theme

2. default theme 里用 frontmatter

```md
---
customLayout: true
---
```
