### ISSUE TITLE
[next] Scroll to anchor not working on vitepress dev

### ISSUE THREAD

**Issue by brc-dd** [vuejs/vitepress#653]
### Reproduction

- Clone and checkout `next-theme`.
- Run  `pnpm i && pnpm build && pnpm docs-dev`.
- Head to `http://localhost:3000/guide/markdown-extensions.html#custom-containers` in a new tab.

### Expected behavior

Links having target anchor should scroll to corresponding header.

### Additional context

Works on production build or if the tab has already the site opened, i.e. doesn't work only on dev mode when opening a new tab.

---

OT: Why is there a `ci-docs` script in package.json? It builds the project twice. `docs-build` should be sufficient in CI envs too.

**Comment by kiaking** [comment]
Confirmed, yeah it's not working 🤔 I think this would be low priority since it works on prod env, but would be really nice if we can fix it.

> OT: Why is there a ci-docs script in package.json? It builds the project twice. docs-build should be sufficient in CI envs too.

Thanks! I don't know too. Seems like we're not using it in our GitHub actions but maybe we're using it in external service...? Not sure. I'll check when we setup VitePress alpha website online and if we don't need it, we can delete it.
