### ISSUE TITLE
[next] Aside curtain not working as expected

### ISSUE THREAD

**Issue by brc-dd** [vuejs/vitepress#656]
Ideally, it should fade out the (aside) content near the screen end. But it doesn't do so:

![image](https://user-images.githubusercontent.com/40380293/170248178-e82d971b-0339-4f30-b58a-6364c66dad0b.png)

It only does that when we are at the end of the (doc) content:

![image](https://user-images.githubusercontent.com/40380293/170248421-1fda360b-eaff-4c74-b19c-acdb1ea1c49c.png)

That curtain is at the bottom of the page instead of being at the bottom of the viewport.

**Comment by brc-dd** [comment]
Fix - change `aside-curtain`'s `position` to `fixed` instead of `absolute`.

**Comment by kiaking** [comment]
Fixed! Ideally, it would be better if we can use `position: sticky`, because in case we want to have like global footer shown at the bottom of the page, this fixed curtain may interfere with it. 

However, since we don't have such footer, and probably we could just overcome the issue with `z-index` on footer, I made it position fixed 👍
