### ISSUE TITLE
contributing error with cjs export

### ISSUE THREAD

**Issue by darrenjennings** [vuejs/vitepress#72]
**Describe the bug**
Spin up vitepress locally to develop

**To Reproduce**
Follow contributing instructions
1. Clone vitepress
2. yarn && yarn link
3. yarn dev

go to new directory and try and link vitepress:

```console
▶ yarn link vitepress
yarn link v1.22.4
warning package.json: No license field
success Using linked package for "vitepress".
✨  Done in 0.06s.

source/repos/kpress  master ✗                                                            6h15m ✖ ⚑ ◒
▶ yarn dev
yarn run v1.22.4
warning package.json: No license field
$ vitepress dev docs
vitepress v0.5.0
vite v1.0.0-rc.3
/Users/darrenjennings/source/repos/vitepress/dist/shared/config.js:23
export function resolveSiteDataByRoute(siteData, route) {
^^^^^^

SyntaxError: Unexpected token export
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/darrenjennings/source/repos/vitepress/dist/node/config.js:11:16)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
Should not throw error.

**System Info**
- vitepress version: v0.5.0
- vite version: v1.0.0-rc.3
- Node version: 12.13.0
- OS version: Mac OS 10.15.3

**Additional context**

**Comment by kiaking** [comment]
Ah, yes you need to first run `yarn dev` at `VitePress` repo before spinning up the linked project. I guess you've skipped "Setup VitePress dev environment" section?

**Comment by kiaking** [comment]
Hmmm. can you try `yarn build` at `vitepress` project, then do `yarn dev` in `source/repos/kpress`? Maybe we need to build first...?

**Comment by darrenjennings** [comment]
@kiaking for whatever reason, I am able to use the src code only by running `yarn dev-node` in isolation without the full `yarn dev` command which runs all the dev commands in parallel: `run-p dev-client dev-client-copy dev-node dev-shared`

**Comment by kiaking** [comment]
Oh, OK I just confirmed at, my side as well. Yeah it's throwing the error you've mentioned... I'll look into it.

**Comment by kiaking** [comment]
This is hard one, couldn't come up with good solution here.

@antfu I finally understood the problem you had when adding `shared` codes. The problem with this issue is that when executing `yarn dev`, client compile is done after the node compile so the `shared` code is compiled as ESNEXT, hence the server is complaining about the `export` syntax.

The `exclude` option in client's `.tsconfig` doesn't work because the code is imported in client's source code, which make it to compile the `shared` code even it's in `exclude` option.

I've tried several things like copying `shared` codes into `client` and `node` before compiling, or trying to tweak client's `tsconfig` to use `commonjs` or `system` module mode, but it get really ugly 😢 

Maybe we should just simply keep the duplicated code on each client and node folder...? `shared/config.ts` is fairly small so it might be easier to just remember to update 2 files rather than trying to create more complex build system... What do you think?

**Comment by antfu** [comment]
Uhm, it indeed tough. 😅

Duplicating code is not very ideal for the long term IMHO. Wondering if it's possible to setup rollup or tsup for vitepress? The pain would not longer exist then. Happy to do so if needed.

**Comment by kiaking** [comment]
> Wondering if it's possible to setup rollup or tsup for vitepress? The pain would not longer exist then. Happy to do so if needed.

Yeah maybe it's time to do that! It would be super awesome if you can do it 👍

**Comment by songololo** [comment]
Also running into this issue, is there a recommended temporary workaround that might suffice for the time being?

Thanks!
