### ISSUE TITLE
[Feature Request] Diff and Language Highlights

### ISSUE THREAD

**Issue by jd-solanki** [vuejs/vitepress#830]
### Is your feature request related to a problem? Please describe.

> This is same as https://github.com/vuejs/vuepress/issues/2704

That issue was for prism but VitePress uses shiki. Is it possible to achieve language highlight with diff language?

### Describe the solution you'd like

na

### Describe alternatives you've considered

na

### Additional context

I use language highlighting for now instead of showing diff because without language highlight diff looks really bad. It takes some time for users to under what changes between two snippets but it's better highlighted.

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

**Comment by brc-dd** [comment]
It turns out shiki has support for this: https://github.com/shikijs/shiki/pull/259. Will take some time but I think it can be integrated here. It might also simplify our [highlightLines plugin](https://github.com/vuejs/vitepress/blob/main/src/node/markdown/plugins/highlightLines.ts).

**Comment by jd-solanki** [comment]
Glad to hear that ❤️

**Comment by brc-dd** [comment]
Okay, just tested this, gonna take back my words. That shiki support won't work for us. To support diffs with syntax highlighting, we'll need to highlight code without `+`, `-`, `@@` and all that, so that syntax highlighter don't break. Then add bg to lines accordingly. This is a lot of work actually. Parsing the diff will be a challenge for sure. Also, GitHub too doesn't syntax highlights diffs. It adds the background colors though. But in our case too, we have that red/green thing, though with text color instead of background.

Consider using this for now:

````
```diff {2-4}
@@ -4,6 +4,5 @@
-    let foo = bar.baz([1, 2, 3]);
-    foo = foo + 1;
+    const foo = bar.baz([1, 2, 3]) + 1;
     console.log(`foo: ${foo}`);
```
````

It looks great even without the code being syntax highlighted:

![image](https://user-images.githubusercontent.com/40380293/174850643-15f9ae89-6ce2-4ee1-baca-a99e17f6f5c9.png)

I am closing this as not-planned. Might visit this later if there is enough demand.
